name: Rust

on:
  push:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive  
      continue-on-error: true        
    - name: Update submodules
      id: update
      run: git submodule update --remote --recursive
      continue-on-error: true
    - name: Build
      run: |
      cd kuksa_app
      cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
