name: Rust

on:
  push:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive    
    - name: Update submodules
      id: update
      run: git submodule update --remote --recursive
      continue-on-error: true
    - name: Prepare
      run: cd kuksa_app
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
